name: simple_internet_checker
description: A package to check internet with connectivity changes as well as pinging to google. The package allows the functionality to check the internet connection of a app.
repository: https://github.com/IchinoseBinit/simple_internet_checker
homepage: https://binitkoirala.com.np

version: 0.0.2

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^3.0.3
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
